#!/bin/bash
# author:Labradors
# url:blog.labradors.work
mkdir /etc/supervisord 
echo "[include]" > /etc/supervisord.conf 
echo "files = /etc/supervisord/*.conf" > /etc/supervisord.conf 
touch /etc/supervisord/ssr.conf 
echo "[program:ssr]" > /etc/supervisord/ssr.conf 
echo "directory=/root/shadowsocks" > /etc/supervisord/ssr.conf 
echo "command = python server.py" > /etc/supervisord/ssr.conf 
echo "user = root" > /etc/supervisord/ssr.conf 
echo "autostart = true" > /etc/supervisord/ssr.conf 
echo "autoresart = true" > /etc/supervisord/ssr.conf 