#!/bin/bash
# author:Labradors
# url:blog.labradors.work
apt-get update
echo Y | apt-get upgrade
echo Y | apt-get install wget lsof curl
cd ~
# curl -fsSL get.docker.com -o get-docker.sh
# sh get-docker.sh --mirror Aliyun
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update
apt-get install docker-ce
# 判断是14还是16
version = $(lsb_release -sc)
if [$version == "xenial"]
then
    systemctl enable docker
    systemctl start docker
	echo "true"
else
	service docker start
fi
usermod -aG docker $USER
docker pull doublemine/shadowsocks:base
mkdir .ssmgr && cd .ssmgr
wget https://raw.githubusercontent.com/Labradors/Script/master/shadowsocks/ss.yml
wget https://raw.githubusercontent.com/Labradors/Script/master/shadowsocks/Dockerfile
docker build -t ss-server .
docker run --rm --net=host --name test ss-server -m aes-256-gcm -v -t 3600 -u -p 6001 --fast-open --obfs tls --dns1 8.8.8.8 --dns2 8.8.4.4
